const generatedNodes = [
  {
    id: "node_",
    label: "Classifieds",
    previewText: "Preview text for Classifieds",
    url: "Classifieds.html",
  },
  {
    id: "node_",
    label: "The Need for Indifference",
    previewText: "Preview text for The Need for Indifference",
    url: "The Need for Indifference.html",
  },
  {
    id: "node_",
    label: "The 80-hour Myth",
    previewText: "Preview text for The 80-hour Myth",
    url: "The 80-hour Myth.html",
  },
  {
    id: "node_",
    label: "Lawyers or Insurance Salesmen",
    previewText: "Preview text for Lawyers or Insurance Salesmen",
    url: "Lawyers or Insurance Salesmen.html",
  },
  {
    id: "node_",
    label: "How to Angel Invest, Part 1",
    previewText: "Preview text for How to Angel Invest, Part 1",
    url: "How to Angel Invest, Part 1.html",
  },
  {
    id: "node_",
    label: "Bill Burnham on the future of Google Base",
    previewText: "Preview text for Bill Burnham on the future of Google Base",
    url: "Bill Burnham on the future of Google Base.html",
  },
  {
    id: "node_",
    label: "Craigslist is Worth More than EBay",
    previewText: "Preview text for Craigslist is Worth More than EBay",
    url: "Craigslist is Worth More than EBay.html",
  },
  {
    id: "node_",
    label: "On Meditation",
    previewText: "Preview text for On Meditation",
    url: "On Meditation.html",
  },
  {
    id: "node_",
    label: "Vast.com launches Credit Card Search!",
    previewText: "Preview text for Vast.com launches Credit Card Search!",
    url: "Vast.com launches Credit Card Search!.html",
  },
  {
    id: "node_",
    label: "Bubble",
    previewText: "Preview text for Bubble",
    url: "Bubble.html",
  },
  {
    id: "node_",
    label: "The truth about hard work",
    previewText: "Preview text for The truth about hard work",
    url: "The truth about hard work.html",
  },
  {
    id: "node_",
    label: "Introducing Venture Hacks",
    previewText: "Preview text for Introducing Venture Hacks",
    url: "Introducing Venture Hacks.html",
  },
  {
    id: "node_",
    label: "There is No Angel Bubble. There are Many Angel Bubbles.",
    previewText:
      "Preview text for There is No Angel Bubble. There are Many Angel Bubbles.",
    url: "There is No Angel Bubble. There are Many Angel Bubbles..html",
  },
  {
    id: "node_",
    label: "The Box",
    previewText: "Preview text for The Box",
    url: "The Box.html",
  },
  {
    id: "node_",
    label: "Why (Private) Investors are Herd Animals",
    previewText: "Preview text for Why (Private) Investors are Herd Animals",
    url: "Why (Private) Investors are Herd Animals.html",
  },
  {
    id: "node_",
    label: "Matt Ridley How Innovation Works, Part 1",
    previewText: "Preview text for Matt Ridley How Innovation Works, Part 1",
    url: "Matt Ridley How Innovation Works, Part 1.html",
  },
  {
    id: "node_",
    label: "On Humility",
    previewText: "Preview text for On Humility",
    url: "On Humility.html",
  },
  {
    id: "node_",
    label: "Be Chaotic Neutral",
    previewText: "Preview text for Be Chaotic Neutral",
    url: "Be Chaotic Neutral.html",
  },
  {
    id: "node_",
    label: "Who has time for meetings",
    previewText: "Preview text for Who has time for meetings",
    url: "Who has time for meetings.html",
  },
  {
    id: "node_",
    label: "Yes, the bubble is back",
    previewText: "Preview text for Yes, the bubble is back",
    url: "Yes, the bubble is back.html",
  },
  {
    id: "node_",
    label: "A Founder’s Anxiety",
    previewText: "Preview text for A Founder’s Anxiety",
    url: "A Founder’s Anxiety.html",
  },
  {
    id: "node_",
    label: "VC Bundling",
    previewText: "Preview text for VC Bundling",
    url: "VC Bundling.html",
  },
  {
    id: "node_",
    label: "Kapil Gupta Conquering the Mind",
    previewText: "Preview text for Kapil Gupta Conquering the Mind",
    url: "Kapil Gupta Conquering the Mind.html",
  },
  {
    id: "node_",
    label: "We Should All Be Working for Ourselves",
    previewText: "Preview text for We Should All Be Working for Ourselves",
    url: "We Should All Be Working for Ourselves.html",
  },
  {
    id: "node_",
    label: "Web 2.0 + Web 2.0 = Web 3.0",
    previewText: "Preview text for Web 2.0 + Web 2.0 = Web 3.0",
    url: "Web 2.0 + Web 2.0 = Web 3.0.html",
  },
  {
    id: "node_",
    label: "Two More Hacks",
    previewText: "Preview text for Two More Hacks",
    url: "Two More Hacks.html",
  },
  {
    id: "node_",
    label: "Matt Ridley How Innovation Works, Part 2",
    previewText: "Preview text for Matt Ridley How Innovation Works, Part 2",
    url: "Matt Ridley How Innovation Works, Part 2.html",
  },
  {
    id: "node_",
    label: "Why We May Think",
    previewText: "Preview text for Why We May Think",
    url: "Why We May Think.html",
  },
  {
    id: "node_",
    label: "Principal-Agent Problem Act Like an Owner",
    previewText: "Preview text for Principal-Agent Problem Act Like an Owner",
    url: "Principal-Agent Problem Act Like an Owner.html",
  },
  {
    id: "node_",
    label: "Envy Can Be Useful, or It Can Eat You Alive",
    previewText: "Preview text for Envy Can Be Useful, or It Can Eat You Alive",
    url: "Envy Can Be Useful, or It Can Eat You Alive.html",
  },
  {
    id: "node_",
    label: "Unquantifiable Risk",
    previewText: "Preview text for Unquantifiable Risk",
    url: "Unquantifiable Risk.html",
  },
  {
    id: "node_",
    label: "New year, new blog",
    previewText: "Preview text for New year, new blog",
    url: "New year, new blog.html",
  },
  {
    id: "node_",
    label: "Craigslist takes on Sand Hill Road",
    previewText: "Preview text for Craigslist takes on Sand Hill Road",
    url: "Craigslist takes on Sand Hill Road.html",
  },
  {
    id: "node_",
    label: "How to Angel Invest, Part 2",
    previewText: "Preview text for How to Angel Invest, Part 2",
    url: "How to Angel Invest, Part 2.html",
  },
  {
    id: "node_",
    label: "STIRR discovers Price Discrimination",
    previewText: "Preview text for STIRR discovers Price Discrimination",
    url: "STIRR discovers Price Discrimination.html",
  },
  {
    id: "node_",
    label: "Do Animals Laugh",
    previewText: "Preview text for Do Animals Laugh",
    url: "Do Animals Laugh.html",
  },
  {
    id: "node_",
    label: "Isn’t it obvious what Web 2.0 is",
    previewText: "Preview text for Isn’t it obvious what Web 2.0 is",
    url: "Isn’t it obvious what Web 2.0 is.html",
  },
  {
    id: "node_",
    label: "Natural Beauty",
    previewText: "Preview text for Natural Beauty",
    url: "Natural Beauty.html",
  },
  {
    id: "node_",
    label: "Read the Best 100 Books Over and Over Again",
    previewText: "Preview text for Read the Best 100 Books Over and Over Again",
    url: "Read the Best 100 Books Over and Over Again.html",
  },
  {
    id: "node_",
    label: "Life Formulas I",
    previewText: "Preview text for Life Formulas I",
    url: "Life Formulas I.html",
  },
  {
    id: "node_",
    label: "Reject Most Advice",
    previewText: "Preview text for Reject Most Advice",
    url: "Reject Most Advice.html",
  },
  {
    id: "node_",
    label: "The Unbundling of the Venture Capital Industry",
    previewText:
      "Preview text for The Unbundling of the Venture Capital Industry",
    url: "The Unbundling of the Venture Capital Industry.html",
  },
];
